apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-spring-boot-app
spec:
  project: default
  source:
    repoURL: https://github.com/your/repo
    targetRevision: main
    path: java-maven-sonar-argocd-helm-k8s/spring-boot-app-manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: your-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
